kind: Deployment 
apiVersion: apps/v1
metadata: 
 name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: johny
  template:
    metadata:
      name: test1
      labels:
        name: johny
    spec:
      containers:
        - name: c001
          image: httpd
          ports:
            - containerPort: 80
