apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: npapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: npapp
  template:
    metadata:
      labels:
        app: npapp
    spec:
      containers:
        - name: myapp-con
          image: httpd
          ports:
            - containerPort: 3000
