apiVersion: v1
kind: ConfigMap
metadata:
  name: ex-config
data:
  database: mongodb
  database_url: mongodb://localhost:27017

---

kind: Pod
apiVersion: v1
metadata:
  name: cm-env-var-pod
spec:
  containers:
    - name: env-var-con
      image: nginx
      envFrom:
        - configMapRef:
             name: ex-config

