apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
    - name: cm-pod-con
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
         - name: html-from-cm
           mountPath: /usr/share/nginx/html/
           readOnly: true
  volumes:
    - name: html-from-cm
      configMap:
        name: dev-html

