apiVersion: v1
kind: Pod
metadata:
  name: myvolsecret
spec:
  containers:
    - name: con1
      image: centos
      command: ["/bin/bash", "-c", "while true; do echo hiii; sleep 10; done"]
      volumeMounts:
        - name: testsecret
          mountPath: "/tmp/mysecrets"
  volumes:
    - name: testsecret
      secret:
       secretName: mysecret
