kind: Pod
apiVersion: v1
metadata:
  name: multiconpod
spec:
  containers:
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hi rakesh; sleep 10; done"]
    - name: c02
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo good morning; sleep 20; done"]
