apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: myvol-con
      image: tomcat:8.5
      volumeMounts:
        - name: pv
          mountPath: "/usr/local/tomcat/logs"
  volumes:
    - name: pv
      persistentVolumeClaim:
        claimName: my-pvc
