apiVersion: v1
kind: PersistentVolume  # Corrected spelling
metadata:
  name: my-pv
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle  # Corrected spelling
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/pvdata
