kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myreplicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      name: temp1Prod
  template:
    metadata:
      name: templateforreplica
      labels:
        name: temp1Prod
    spec:
      containers:
        - name: php-redis
          image: nginx
