apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  replicas: 8
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-con
          image: redis:latest
          ports:
            - containerPort: 80

